language: node_js
node_js:
  - '9'
  - '8'
  - '10'
script:
  - npm run lint
cache:
  npm: true
  directories:
    - node_modules
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
